name: Chocolatine
on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'
env:
  EXECUTABLES: "push_swap"
jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Coding Style
        run: |
            rm -rf coding_style_errors.txt
            check.sh $(pwd) $(pwd)
            exit_code=$?
            echo $exit_code
            if [ $exit_code -ne 0 ];then
            coding_style_output=$(cat coding_style_errors.txt)
            echo "::error file=app.js,line=1,col=1::${coding_style_output}"
            exit $exit_code
            fi

  check_program_compilation:
    runs-on: ubuntu-latest
    needs: check_coding_style
    if: success()
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: make
      - name: Clean
        run: make clean
      - name: Execute
        run: |
          for executable in $EXECUTABLES; do
          if [ ! -x "./$executable" ]; then
          echo "Error: $executable does not exist or is not executable"
          exit 1
          fi
          done

  run_tests:
    runs-on: ubuntu-latest
    needs: check_program_compilation
    if: success()
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        uses: docker://epitechcontent/epitest-docker:latest
        with:
          entrypoint: "/bin/bash"
          args: "-c 'make tests_run'"
